### ISSUE TITLE
User can upload a photo

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be prompted to take a photo of themselves before and after a run.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If user clicks on "go run" they will be brought to a page with text that says to take a pre-exercise photo and show their camera. When the photo is taken there will be options to continue or retake it. If the user selects to retake it, they will return to taking a photo. If the user selects to accept the photo, they will proceed to feature 2, tracking their run.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1668" alt="Feature 1_ User can upload a photo" src="https://user-images.githubusercontent.com/24307282/200437262-e629cd1e-814f-4cb1-8fde-3bd244d09fc0.png">

<img width="5984" alt="Feature 1_ User can upload a photo (1)" src="https://user-images.githubusercontent.com/24307282/200440512-f472e69e-8a65-45f0-bfc1-f2d0be5b77d4.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to show the splash screen
- [x] Create a component to show the "go run" page
- [x] Create a component to show the "home" page
- [x] Create a component to show the navbar
- [x] Update navbar component to have the title RunnerFuze
- [x] Update navbar component to have a home icon
- [x] Update splash screen component to include buttons that link to "home" page and "go run" page
- [x] Update "go run" component to show text explaining important details to the user
- [x] Update "go run" component to access the users camera (front-facing if possible)
- [x] Update "go run" component to ask the user to take a pre-exercise photo
- [x] Update "go run" component to include three buttons (flash, take picture, and switch the facing of the camera)
- [x] Update logic of "go run" component to ask the user if the photo they took "looks good" and swap the three buttons to two buttons that have a check icon and a redo icon.
- [x] Update logic of "go run" component to return to taking a photo if the redo icon is clicked
- [x] Update logic of "go run" component when check icon is clicked to store the image file in indexedDb local storage

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that the image can be previewed while it is in indexedDb by using an ObjectURL.
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
