### ISSUE TITLE
User can sign in

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon entering app the user will see a button to sign in. If the user clicks that button a modal will appear with a username and password input text box. If the user has signed up they can enter their information and hit login to be signed in as a user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 10_ User can sign in](https://user-images.githubusercontent.com/24307282/202309132-d32a40f0-da8e-416e-8345-2dbb557ef0d4.png)
![Feature 10_ User can sign-in](https://user-images.githubusercontent.com/24307282/202309142-8aa51761-9646-40d7-8042-21e8321fbe7c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to have a post route for authenticating signing in
- [x] Have the sign in post route contact the database and retrieve the account information for that username
- [x] With the account information, check that the password the user entered can be turned into the hashedPassword
- [x] If the user entered the correct information send a token and a payload in a response back to the client
- [x] Test with HTTPie to make sure the sign in post route is functioning
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update sign up modal to function as a sign in modal when the state of user changes
- [x] Change title of modal to sign in from sign up
- [x] Change register button to login button
- [x] Add a clickable link with the text "register" to switch to sign up modal if the user does not have an account
- [x] When the login button is clicked fetch with a post request to the sign in authentication route on the server
- [x] Send the server sign in route the username and password
- [x] If the user successfully signed in, show splash screen with buttons "home" and "go run"

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
