### ISSUE TITLE
User can sign out

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The navbar will have an icon indicating a sign out. If the user clicks the sign out icon they will have their token cleared from localstorage and they will return to the splash screen with the buttons sign up and sign in.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 11_ User can sign out](https://user-images.githubusercontent.com/24307282/202520432-03c47173-3368-4a74-95b8-72d409f131b3.png)
![Feature 11_ User can sign-out](https://user-images.githubusercontent.com/24307282/202520454-404824f7-dc41-4bde-a810-a25f778bf380.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a button that has the sign out icon and put it in the navbar
- [x] Update button logic so that onClick the token in the localstorage is cleared, the state of userLogin is reset to null, and there is a hash change to the splash screen.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
