### ISSUE TITLE
User can track their runs

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can track their runs.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After taking a pre-exercise photo the user will see a timer for when they want to start their run. When the user hits start, the timer will begin counting. The user then runs for however long they desire and hits stop when they are done with the run.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="7192" alt="Feature 2_ User can track a run (1)" src="https://user-images.githubusercontent.com/24307282/200947581-6e87f1df-5ea6-4bc6-8330-1b2fb4fd068b.png">
<img width="2961" alt="Feature 2_ User can track a run" src="https://user-images.githubusercontent.com/24307282/200947584-9fa2ecc8-9c94-4b1e-88b4-9d5e4441ba6c.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to act as a stopwatch
- [x] Create a state variable to hold the current time
- [x] Modify the state variable when the stopwatch is going
- [x] Create button component for starting the stopwatch
- [x] Create button component for stopping the stopwatch
- [x] Create button component for pausing the stopwatch
- [x] Create button component for resuming the stopwatch
- [x] Create button component for finishing with the exercise
- [x] Create function that gets coordinates of user when called
- [x] Set an interval that gets the users coordinates every unit of time
- [x] Set up a service worker to cache the page to continue working if the user loses connection
- [x] Update coordinates in indexedDb every unit of time during the run
- [x] Save coordinates in indexedDb when the run is finished
- [x] Prompt the user to take another photo
- [x] Calculate distance and pace
- [x] Build map with coordinates drawn on it with a polyline
- [x] Snap a screenshot of the map with the route
- [x] Display statistics to user along with pre-run image, route image, post-run image.
- [x] Add nosleep.js to make sure the screen remains on when the user runs

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
