### ISSUE TITLE
User can save their runs

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save their runs

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will see a button that says "SAVE" at the end of their run. If they click the button their run will be stored in a tab on the navbar that looks like a bookmark. When clicking on the bookmark, all their runs tied to their account will populate the page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="2530" alt="Feature 3_ User can save runs" src="https://user-images.githubusercontent.com/24307282/201402351-6b79062f-6409-4ad8-baf9-16d7b1e0bfb0.png">
<img width="7192" alt="Feature 3_ User can save a run" src="https://user-images.githubusercontent.com/24307282/201402358-69c8cbbc-6a64-4737-9a1e-c1edd5cc13eb.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to import the tables and columns from dbdesigner
- [x] Update `data.sql` to create a dummy username and password account for testing

### ☁️ Server Tasks

- [x] Update `server/index.js` to receive post requests with run data
- [x] Update `server/index.js` to update the database upon receiving a post request with run data
- [x] Update `server/index.js` to receive get requests for run data
- [x] Update `server/index.js` to gather run data from the database upon receiving a get request for run data
- [x] Test if the database inserts posted data with httpie
- [x] Test if the database gives data with httpie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update navbar component to have a bookmark icon
- [x] Create component for saved runs page
- [x] Update bookmark icon to swap to saved runs page
- [x] Update save button to swap to saved runs page
- [x] Update save button to send a post request to server with run data
- [x] Update save page to send a get request to server to retrieve run data
- [x] Update save page to show run data on the page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [ ] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
