### ISSUE TITLE
User can post their runs

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can post runs.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After tracking their run, on the statistics page the user will see options to "save" or "post" their run. If they click "post" their run will be saved then the "post" page will be displayed where the user can choose what they want to post from their run. If the user hits save they will be brought to a "saved" run page where they can choose to "post" from their saved runs.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 4_ User can post runs](https://user-images.githubusercontent.com/24307282/201751626-1c652a60-43e5-4efd-b019-62b5edc0d69e.png)
![Feature 4_ User can post runs (1)](https://user-images.githubusercontent.com/24307282/201751632-7e3b5504-caf9-45a5-aa69-5082d78a45bf.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to have a post route to store data in the posts table in the database
- [x] Update `server/index.js` to have a get route to retrieve run from the runs table in the database
- [x] Update `server/index.js` to have a get route to retrieve post from the posts table in the database
- [x] Test the post route with HTTPie
- [x] Test the get route with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to show the "new post" page
- [x] Update "new post" component to fetch data about the run before displaying
- [x] Update "new post" component to show run data on the post page
- [x] Update "new post" component to have a form element with a caption
- [x] Update "new post" component to post data about the post when the user clicks post :)
- [x] Update "new post" component to view swap to home page after posting
- [x] Update "home" component to fetch data about posts
- [x] Update "home" component to display data about posts
- [x] Update "home" component logic to show new posts first

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
