### ISSUE TITLE
User can edit their posts

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit a post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will see their posts on the homepage. On their posts there will be a horizontal ellipsis. If the user clicks the horizontal ellipsis they will see an option to edit.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 5_ User can edit their post](https://user-images.githubusercontent.com/24307282/202057144-4fdd7ae3-b237-430c-b8ae-8716a61b0406.png)

![Feature 5_ User can edit their post (1)](https://user-images.githubusercontent.com/24307282/202059001-413eb47c-a5d7-4f8c-829f-6d265053fe73.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to get single posts based on the postId
- [x] Update get route to verify the accountId by searching the db for the account associated with the postId and comparing that accountId to req.user.accountId
- [x] Update get route to retrieve post data from the post table in the database and return it to client
- [x] Update `server/index.js` to receive put requests to modify posts with the postId
- [x] Update put route to verify the accountId by searching the db for the account associated with the postId and comparing that accountId to req.user.accountId
- [x] Update put route to update the data in the post table of the database and give a response to the client
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add horizontal ellipsis to the top right corner of posts for the currently logged in user
- [x] When the user clicks the ellipsis have a dropdown menu with an option for edit
- [x] When the user clicks edit, switch the page to the edit post view of the post page
- [x] Update "post" page component to be modified to show "edit post" instead of "new post"
- [x] Update "post" page component to fill the caption with caption data when in "edit" mode
- [x] Update "post" page component to say "update" instead of "post" when in "edit" mode
- [x] Update database when "update" button is clicked by fetching with the put method.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
