### ISSUE TITLE
User can remove post

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click a horizontal ellipse on their post and see the option of remove. If they click remove there will be a confirmation. If the user confirms the action then the post will be removed.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 6_ User can remove their post](https://user-images.githubusercontent.com/24307282/202787565-83d3b030-4ae2-4c66-b163-feab640fcfcb.png)
![Feature 6_ User can remove their post (1)](https://user-images.githubusercontent.com/24307282/202787572-7ea605a9-239f-4f95-a00e-07c813f865b8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to have a delete route that takes in a postId
- [x] Have the delete route contact the database and tell it to remove that post
- [x] Have the delete route respond to the client with success or failure
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update ellipsis to have the option of remove
- [x] When remove is clicked, open a modal that confirms the user wants to remove the post
- [x] If the user hits cancel then the modal closes
- [x] If the user hits proceed then the delete route on the server is fetched with the method of delete and the postId
- [x] Rerender once the post has been deleted

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
