### ISSUE TITLE
User can like a post

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can like a post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will see a heart icon below each post. If the user clicks the heart icon they will like the post and the heart icon will be filled in for them. If the user clicks a filled in heart icon, the post will be unlikes and the heart icon will return to a not filled in state.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 7_ User can like a post](https://user-images.githubusercontent.com/24307282/202814794-35d07de4-792d-40a1-8ff0-5be9dc69bdd4.png)
![Feature 7_ User can like posts](https://user-images.githubusercontent.com/24307282/202814802-e524b65c-b100-4496-b555-fe08c3966ad4.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to have a post route for likes
- [x] Have the post route insert into the likes table in the database with the postId and accountId
- [x] Verify the using req.user in the backend
- [x] Respond to the client if the database query was successful or not
- [x] Update `server/index.js` to have a delete route for likes
- [x] Have the delete route remove a like from the likes table using the postId and accountId
- [x] Verify the using req.user in the backend
- [x] Respond to the client if the removal of the like was successful or not
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a like icon component
- [x] Have the state of the icon default to not liked and show an empty heart icon
- [x] Have the state of the icon show a filled heart when liked
- [x] Have the state of the icon change when a user clicks on the heart icon

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
