### ISSUE TITLE
User can sign up

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be prompted to sign in or sign up upon entering the app. If the user clicks sign up, a modal will appear with inputs for username, and password. The user will be able to fill out the forms and hit register to create an account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 9_ User can sign-up](https://user-images.githubusercontent.com/24307282/202283399-38f0b591-67af-40ea-b3ff-a5df1a5506b0.png)
![Feature 9_ User can sign up](https://user-images.githubusercontent.com/24307282/202283434-c76e11af-521f-4eaf-90c3-3ace158d26ff.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to have a post route for signing up
- [x] Update post route to insert into the database a new account
- [x] Update post route to send a response to the client of everything except the hashedpassword
- [x] Test with HTTPie to make sure the post route works
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update homepage component to show a sign up button
- [x] Create sign up modal containing a form element with input elements for email, username, password
- [x] Add onClick to button that opens the sign up modal
- [x] Add onClick to register to fetch a post route to the sign-up post route
- [x] If response from server is success, then tell the user their account has been created.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
